### ISSUE TITLE
tests for 5d var_read functions

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-ncio#43]
We don't have tests for these functions.

**Comment by edwardhartnett** [comment]
@CoryMartin-NOAA any progress here? I would like to get testing for this library done and dusted...

**Comment by CoryMartin-NOAA** [comment]
Not yet... I think @jswhit suggested that we should modify the documentation to specify that 5D is the max (if that hasn't been done already) and since there isn't a 5D variable in the test input file, we'll need to create a 5D variable with the nf90 library calls and then read it with the ncio read function.

**Comment by CoryMartin-NOAA** [comment]
In attempting to add a test to read a 5D var, I'm running into an issue. I created a new dimension and 5D variable using python with the sample file. But now, the library is unable to properly handle the file. It says the variable's ndim attribute is -1068507643 which obviously isn't right. I'll push the file to the branch feature/read_5d_test

**Comment by CoryMartin-NOAA** [comment]
Never mind, I'm dumb... didn't realize the ctest was a copied netCDF file and not a symlink.

**Comment by arunchawla-NOAA** [comment]
Looks like this test is complete ? Can this issue be closed?

**Comment by jswhit** [comment]
I think this can be closed
